base_domain: test

mysql_host: 192.168.56.10
postgresql_host: 192.168.56.11
planningalerts_db_host: 192.168.56.11

newrelic_license_key: null
devsite: true
rds_admin_password: "test_password"
nrinfragent_state: absent
