# File: group_vars/openaustralia_old.yml
---

# TODO: Move default values here to make sure they don't change

ruby_manager: rvm

# Based on aws_eip.main.public_ip and CNAMES in terraform/openaustralia/dns.tf
#


production_server_aliases:
  - "{{ openaustralia_domain }}"

extra_production_server_aliases:
  - www.openaustralia.org
  - openaustralia.org

combined_production_server_aliases: >-
  {{ production_server_aliases +
     ((base_domain == 'org.au') | ternary(extra_production_server_aliases, [])) }}

staging_server_aliases:
  - "www.test.{{ openaustralia_domain }}"

extra_staging_server_aliases:
  - test.openaustralia.org

combined_staging_server_aliases: >-
  {{ staging_server_aliases +
     ((base_domain == 'org.au') | ternary(extra_staging_server_aliases, [])) }}

extra_data_server_aliases:
  - data.openaustralia.org

extra_software_server_aliases:
  - software.openaustralia.org

xapian_version: 1.2.22

# PHP has two version numbers :( - make sure they are in sync
php_version: 5.6
php_api_version: "20131226"

apache_sites:
  production:
    # CNAME, but this is the canonical name !?
    domain: "www.{{ openaustralia_domain }}"
    #cert_domain: "{{ openaustralia_domain }}"
    server_aliases: "{{ combined_production_server_aliases }}"
    newrelic_appname: OpenAustralia.org
  staging:
    domain: test."{{ openaustralia_domain }}"
    password_protect: true
    server_aliases: "{{ combined_staging_server_aliases }}"
    template: production
    newrelic_appname: 'OpenAustralia.org Staging'
  "000-default":
    # redirects to another domain
    domain: "www.{{ openaustralia_domain }}"
    server_aliases: []
  blog:
    domain: blog.openaustralia.org
    server_aliases: []
  data:
    domain: "data.{{ openaustralia_domain }}"
    server_aliases: "{{ (base_domain == 'org.au') | ternary(extra_data_server_aliases, []) }}"
  software:
    domain: "software.{{ openaustralia_domain }}"
    server_aliases: "{{ (base_domain == 'org.au') | ternary(extra_software_server_aliases, []) }}"

