# Staging environment configuration for RightToKnow
# Most values inherited from righttoknow.yml
name: staging.righttoknow.org.au

# Use the same github users as production
github_users:
  [
    "benrfairless",
    "br3nda",
    "jamezpolley",
    "jattree",
    "mlandauer",
    "simonzippy",
  ]

# Disable cron for staging initially
cron_enabled: false

# Staging-specific settings
# Both staging and production environments run in Rails production mode
rails_env: production

# Domain configuration for standalone staging server
righttoknow_domain: staging.righttoknow.org.au
domain: staging.righttoknow.org.au

# Disable backups for staging
backup_profiles: []

# Use staging SSL certificates
certbot_webserver: nginx
certbot_webroot: /usr/share/nginx/html
certbot_domains:
  - staging.righttoknow.org.au

# NOTE: For staging, you'll need to add encrypted secrets here similar to production
# You can copy from production and modify, or generate new ones:
# - db_password_production
# - db_password_staging  
# - alaveteli_cookie_store_session_secret
# - alaveteli_secret_key_base
# - alaveteli_recaptcha_private_key
# - alaveteli_incoming_email_secret
# - alaveteli_admin_password
#
# For initial testing, you might copy production values and change passwords

# Ansible connection settings for staging server
# ansible_user: ubuntu
# ansible_ssh_private_key_file: "{{ playbook_dir }}/terraform.pem"
