# {{ ansible_managed }}

# Redirect another old domain

<VirtualHost *:80>
    ServerName {{ domain }}
    RedirectMatch permanent ^/$ https://oaf.{{ base_domain }}/blog
    RedirectMatch permanent ^/(.*) https://oaf.{{ base_domain }}/$1

    ErrorLog "/srv/www/production/log/blog_error.log"
    CustomLog "/srv/www/production/log/blog_access.log" combined
</VirtualHost>

<IfModule mod_ssl.c>
    <VirtualHost *:443>
        ServerName {{ domain }}
        RedirectMatch permanent ^/$ https://oaf.{{ base_domain }}/blog
        RedirectMatch permanent ^/(.*) https://oaf.{{ base_domain }}/$1

        ErrorLog "/srv/www/production/log/blog_error.log"
        CustomLog "/srv/www/production/log/blog_access.log" combined

        SSLEngine on
        SSLCertificateKeyFile    /etc/letsencrypt/live/{{ domain }}/privkey.pem
        SSLCertificateFile       /etc/letsencrypt/live/{{ domain }}/fullchain.pem
    </VirtualHost>
</IfModule>
