# Redirect another old domain

<VirtualHost *:80>
    ServerName blog.openaustralia.org
    RedirectMatch permanent ^/$ https://www.openaustraliafoundation.{{ base_domain }}/blog
    RedirectMatch permanent ^/(.*) https://www.openaustraliafoundation.{{ base_domain }}/$1
</VirtualHost>
