# {{ ansible_managed }}

# Redirect another old domain

<VirtualHost *:80>
    ServerName {{ domain }}
    RedirectMatch permanent ^/$ https://oaf.{{ base_domain }}/blog
    RedirectMatch permanent ^/(.*) https://oaf.{{ base_domain }}/$1

    ErrorLog "/srv/www/production/log/blog_error_log"
    CustomLog "/srv/www/production/log/blog_access_log" combined
</VirtualHost>

<IfModule mod_ssl.c>
    <VirtualHost *:443>
        ServerName {{ domain }}
        RedirectMatch permanent ^/$ https://oaf.{{ base_domain }}/blog
        RedirectMatch permanent ^/(.*) https://oaf.{{ base_domain }}/$1

        ErrorLog "/srv/www/production/log/blog_error_log"
        CustomLog "/srv/www/production/log/blog_access_log" combined

        SSLEngine on
        SSLCertificateKeyFile    {{ certbot_live_dir_map[domain] }}/privkey.pem
        SSLCertificateFile       {{ certbot_live_dir_map[domain] }}/fullchain.pem
    </VirtualHost>
</IfModule>
