# {{ ansible_managed }}

# We're not bothering with having an equivalent staging url for data.openasutralia.org.au

{% if server_aliases %}
<VirtualHost *:80>
    ServerName {{ server_aliases[0] }}
    {% for alias in server_aliases[1:] %}
    ServerAlias {{ alias }}
    {% endfor %}

    RedirectMatch permanent ^/(.*) http://{{ domain }}/$1
    ErrorLog "/srv/www/production/log/data_redirect_error.log"
    CustomLog "/srv/www/production/log/data_redirect_access.log" combined
</VirtualHost>
{% endif %}

<VirtualHost *:80>
    ServerName {{ domain }}

    ErrorLog "/srv/www/production/log/data_error.log"
    CustomLog "/srv/www/production/log/data_access.log" combined

    DocumentRoot "/srv/www/production/shared/pwdata"

    <Directory "/srv/www/production/shared/pwdata">
        Options Indexes FollowSymLinks
        IndexOptions FancyIndexing
        AllowOverride None

        Require all granted
    </Directory>
</VirtualHost>

<IfModule mod_ssl.c>
    {% if server_aliases %}
    <VirtualHost *:443>
        ServerName {{ server_aliases[0] }}
        {% for alias in server_aliases[1:] %}
        ServerAlias {{ alias }}
        {% endfor %}

        RedirectMatch permanent ^/(.*) https://{{ domain }}/$1

        SSLEngine on
        SSLCertificateKeyFile    /etc/letsencrypt/live/{{ domain }}/privkey.pem
        SSLCertificateFile       /etc/letsencrypt/live/{{ domain }}/fullchain.pem

        ErrorLog "/srv/www/production/log/data_redirect_error.log"
        CustomLog "/srv/www/production/log/data_redirect_access.log" combined
    </VirtualHost>
    {% endif %}

    <VirtualHost *:443>
        ServerName {{ domain }}

        ErrorLog "/srv/www/production/log/data_error.log"
        CustomLog "/srv/www/production/log/data_access.log" combined

        DocumentRoot "/srv/www/production/shared/pwdata"

        <Directory "/srv/www/production/shared/pwdata">
            Options Indexes FollowSymLinks
            IndexOptions FancyIndexing
            AllowOverride None

            Require all granted
        </Directory>

       SSLEngine on
       SSLCertificateKeyFile    /etc/letsencrypt/live/{{ domain }}/privkey.pem
       SSLCertificateFile       /etc/letsencrypt/live/{{ domain }}/fullchain.pem
    </VirtualHost>
</IfModule>