# {{ ansible_managed }}

# We're not bothering with having an equivalent staging url
<VirtualHost *:80>
    ServerName {{ domain }}
    {% for alias in server_aliases %}
    ServerAlias {{ alias }}
    {% endfor %}
    RedirectMatch permanent / https://openaustralia.github.io/openaustralia/

    ErrorLog "/srv/www/production/log/software_error.log"
    CustomLog "/srv/www/production/log/software_access.log" combined
</VirtualHost>

<IfModule mod_ssl.c>
    <VirtualHost *:443>
        ServerName {{ domain }}
        {% for alias in server_aliases %}
        ServerAlias {{ alias }}
        {% endfor %}
        RedirectMatch permanent / https://openaustralia.github.io/openaustralia/

        SSLEngine on
        SSLCertificateKeyFile    /etc/letsencrypt/live/{{ domain }}/privkey.pem
        SSLCertificateFile       /etc/letsencrypt/live/{{ domain }}/fullchain.pem

        ErrorLog "/srv/www/production/log/software_error.log"
        CustomLog "/srv/www/production/log/software_access.log" combined
    </VirtualHost>
</IfModule>