---
# - name: sudo reload
#   service:
#     name: sudo
#     state: reloaded
- name: nginx restart
  ansible.builtin.service: name=nginx state=restarted

- name: nginx reload
  ansible.builtin.service: name=nginx state=reloaded
