#!/bin/bash
#
### BEGIN INIT INFO
# Provides: purge-varnish
# Required-Start: $local_fs $syslog
# Required-Stop: $local_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: purge-varnish is a daemon purging the Alaveteli varnish cache
# Description: purge-varnish purge the Alaveteli varnish cache
### END INIT INFO
#
# foi-purge-varnish Start the Alaveteli email purge-varnish daemon

NAME=foi-purge-varnish
DAEMON=/home/deploy/.rbenv/shims/ruby
DAEMON_ARGS="/srv/www/current/script/runner --daemon PurgeRequest.purge_all_loop"
PIDFILE=/srv/www/shared/pids/foi-purge-varnish.pid
LOGFILE=/srv/www/shared/log/foi-purge-varnish.log
DUSER=deploy
# Set RAILS_ENV - not needed if using config/rails_env.rb
RAILS_ENV=production

trap "" 1

export PIDFILE LOGFILE RAILS_ENV

quietly_start_daemon() {
    /sbin/start-stop-daemon --quiet --start --pidfile "$PIDFILE" --chuid "$DUSER" --startas "$DAEMON" -- $DAEMON_ARGS
}

start_daemon() {
    /sbin/start-stop-daemon --start --pidfile "$PIDFILE" --chuid "$DUSER" --startas "$DAEMON" -- $DAEMON_ARGS
}

stop_daemon() {
    /sbin/start-stop-daemon --stop --oknodo --pidfile "$PIDFILE"
}

restart() { stop; start; }

case "$1" in
  check)
      quietly_start_daemon
      if [ $? -ne 1 ]
      then
          echo "Alaveteli purge-varnish daemon was not running; now restarted"
          exit 1
      else
          exit 0
      fi
      ;;

  start)
      echo -n "Starting Alaveteli purge-varnish daemon: $NAME"
      start_daemon
      ;;

  stop)
        echo -n "Stopping Alaveteli purge-varnish daemon: $NAME"
        stop_daemon
        ;;

  restart)
      echo -n "Restarting Alaveteli purge-varnish daemon: $NAME"
      stop_daemon
      start_daemon
      ;;

  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart|check}"
    exit 1
    ;;
esac

if [ $? -eq 0 ]; then
    echo .
    exit 0
else
    echo " failed"
    exit 1
fi

