AllCops:
  NewCops: enable
  Exclude:
    - vendor/**/*
    - roles/external/**/*
    - roles/internal/**/templates/**/*

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - Vagrantfile
