# FIRST: check the `vault_identity_list` in `ansible.cfg` using
# `ls -ld .*pass*`
# and make sure you have all the password files you need.
# If you are missing some, then you can override the list using a `.envrc` entry, e.g.:
# export ANSIBLE_VAULT_IDENTITY_LIST=".vault_pass.txt,ec2@.ec2-vault-pass,all@.all-vault-pass"

## THEN

# Run this like so:
# ansible-playbook site.yml

# To only run this for planningalerts:
# ansible-playbook site.yml -l planningalerts

# To only run this for openaustralia:
# ansible-playbook site.yml -l openaustralia

# To show the value of an encrypted variable:
# ansible planningalerts -m debug -a 'var=mysql_password_production'
# Note that some values are different in development
# ansible development -m debug -a 'var=rds_admin_password'
#
# To encrypt a variable to the default vault id (requires ansible >=2.5.0):
#   ansible-vault encrypt_string --encrypt-vault-id default --name name secret
# To encrypt a variable to the EC2 vault id:
#   ansible-vault encrypt_string --encrypt-vault-id ec2 --name name secret
# See ansible.cfg for notes about which vault id to use.

# Use terraform (see terraform directory) to actually provision ec2 infrastructure

# Ensure python3 is available for Ansible (required before gather_facts), with fallback to python2
# If it does fall back, set ansible_python_interpreter to /usr/bin/python in that old group
- hosts: all
  become: true
  gather_facts: false
  tags: python
  tasks:
    - name: Install python3 for Ansible if available, otherwise fallback to python2
      raw: >-
        test -e /usr/bin/python3 ||
        (apt -y update && apt install -y python-is-python3) ||
        test -e /usr/bin/python ||
        apt install -y python-minimal
      changed_when: false

- hosts: ec2
  name: "Install python2 requirements"
  tags:
    - python
    - python2
  become: true
  tasks:
    - name: Install python packages
      apt:
        pkg: "{{ item }}"
        cache_valid_time: 300
      loop:
        - python-pip
        - python-pymysql
        - python-psycopg2
      when: ansible_python_version is version('3', '<')

    - name: Install boto which is required for EC2 stuff (Python 2)
      pip: name=boto
      when: ansible_python_version is version('3', '<')

- hosts: ec2
  name: "Install python3 requirements"
  tags:
    - python
    - python3
  become: true
  tasks:
    - name: Install python packages
      apt:
        pkg: "{{ item }}"
        cache_valid_time: 300
      loop:
        - python3-pip
        - python3-pymysql
        - python3-psycopg2
      when: ansible_python_version is version('3', '>=')

    - name: Install boto3 which is required for EC2 stuff (Python 3)
      pip: name=boto3
      when: ansible_python_version is version('3', '>=')

- hosts: ec2
  name: "Gather RDS facts"
  tags:
    - rds
    - facts
  tasks:
    - name: Get information about the DEPRECATED Mysql 5 instance
      rds:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        command: facts
        instance_name: main-database
        region: "{{ ec2_region }}"
      register: rds_mysql5
      # Run this task even when running ansible-playbook with "--check"
      check_mode: false
      when: "'requires_mysql_5' in group_names"

    - name: Display information about the DEPRECATED Mysql 5 instance
      debug:
        var: "rds_mysql5"
      when: "(show_rds_debug | default(false) | bool) and ('requires_mysql_5' in group_names)"

    - name: Get information about the Mysql 8 instance
      rds:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        command: facts
        instance_name: maindb
        region: "{{ ec2_region }}"
      register: rds_mysql8
      # Run this task even when running ansible-playbook with "--check"
      check_mode: false
      when: "'requires_mysql' in group_names"

    - name: Display information about the Mysql 8 instance
      debug:
        var: "rds_mysql8"
      when: "(show_rds_debug | default(false) | bool) and ('requires_mysql' in group_names)"

    - name: Get information about the postgresql RDS instance
      rds:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        command: facts
        instance_name: postgresql
        region: "{{ ec2_region }}"
      register: rds_postgresql
      # Run this task even when running ansible-playbook with "--check"
      check_mode: false
      when: "'requires_postgresql' in group_names"

    - name: Display information about the postgresql RDS instance
      debug:
        var: "rds_postgresql"
      when: "(show_rds_debug | default(false) | bool) and ('requires_postgresql' in group_names)"

    - name: Get information about the planningalerts RDS instance
      rds:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        command: facts
        instance_name: planningalerts
        region: "{{ ec2_region }}"
      register: rds_planningalerts
      # Run this task even when running ansible-playbook with "--check"
      check_mode: false
      when: "'requires_postgresql' in group_names"

    - name: Displays information about the planningalerts RDS instance
      debug:
        var: "rds_planningalerts"
      when: "(show_rds_debug | default(false) | bool) and ('requires_postgresql' in group_names)"

- hosts: all
  become: true
  tags: base-server
  name: "Install base server packages"
  roles:
    - internal/base-server

# Change to expecting a variable ruby_versions, which will have the ruby versions to install (set elsewhere)

- hosts: all
  name: "Setup ruby managers and install versions"
  become: true
  roles:
    - role: internal/remove_rbenv
      rbenv_users:
        - deploy
      tags:
        - cleanup
        - ruby
        - rbenv
      when: "ruby_manager != 'rbenv'"

    - role: internal/remove_rvm
      tags:
        - cleanup
        - ruby
        - rvm
      when: "ruby_manager != 'rvm'"

    - role: internal/remove_mise
      tags:
        - cleanup
        - ruby
        - mise
      when: "ruby_manager != 'mise'"

    - role: external/zzet.rbenv
      tags:
        - ruby
        - rbenv
      when: "ruby_manager == 'rbenv'"
      rbenv:
        env: user
        version: v1.1.2
        default_ruby: "{{ ruby_versions | first }}"
        rubies: "{{ ruby_versions | map('community.general.dict_kv', 'version') | list }}"
      rbenv_users:
        - deploy

    - role: external/rvm.ruby
      tags:
        - ruby
        - rvm
      when: "ruby_manager == 'rvm'"
      rvm1_rubies: "{{ ruby_versions }}"
      rvm1_install_flags: "--auto-dotfiles"
      rvm1_install_path: /usr/local/rvm
      rvm1_user: root
      rvm1_gpg_key_server: "hkps://keyserver.ubuntu.com"
      # may need this for planningalerts
      # rvm1_rvm_version: "head"
      # rvm1_gpg_key_server: 'rvm1_gpg_key_server: "hkps://keyserver.ubuntu.com"'

    # Add deploy user to group rvm
    - role: internal/rvm.group
      tags:
        - ruby
        - rvm
      when: "ruby_manager == 'rvm'"

#    - role: install_mise
#      tags:
#        - ruby
#      when: "ruby_manager == 'mise'"
#      mise_ruby_versions: "{{ ruby_versions }}"

# vagrant equivalent of AWS rds_instance
- hosts: mysql
  tags: mysql
  become: true
  roles:
    - mysql

# vagrant equivalent of AWS rds_instance
- hosts: postgresql
  tags: postgresql
  become: true
  roles:
    - postgresql

- hosts: righttoknow
  tags: righttoknow
  become: true
  roles:
    - righttoknow

- hosts: planningalerts
  tags: planningalerts
  become: true
  roles:
    - planningalerts

- hosts: theyvoteforyou
  tags: theyvoteforyou
  become: true
  roles:
    - theyvoteforyou

- hosts: openaustralia
  tags: openaustralia
  become: true
  roles:
    - openaustralia

- hosts: proxy
  tags: proxy
  become: true
  roles:
    - proxy

- hosts: metabase
  tags: metabase
  become: true
  roles:
    - metabase

- hosts: openvpn
  tags: openvpn
  become: true
  roles:
    - internal/openvpn

# vagrant equivalent of AWS redis service
- hosts: redis
  name: "Install redis"
  tags: redis
  become: true
  tasks:
    - name: Install redis
      apt:
        name: redis
    - name: Make redis listen on 0.0.0.0
      lineinfile:
        path: /etc/redis/redis.conf
        regexp: "^bind 127.0.0.1"
        line: "bind 0.0.0.0"
      notify:
        - Restart redis
  handlers:
    - name: Restart redis
      service:
        name: redis
        state: restarted
