# FIRST: check the `vault_identity_list` in `ansible.cfg` using
# `ls -ld .*pass*`
# and make sure you have all the password files you need.
# If you are missing some, then you can override the list using a `.envrc` entry, e.g.:
# export ANSIBLE_VAULT_IDENTITY_LIST=".vault_pass.txt,ec2@.ec2-vault-pass,all@.all-vault-pass"

## THEN

# Run this like so:
# ansible-playbook site.yml

# To only run this for planningalerts:
# ansible-playbook site.yml -l planningalerts

# To only run this for openaustralia:
# ansible-playbook site.yml -l openaustralia

# To show the value of an encrypted variable:
# ansible planningalerts -m debug -a 'var=mysql_password_production'
# Note that some values are different in development
# ansible development -m debug -a 'var=rds_admin_password'
#
# To encrypt a variable to the default vault id (requires ansible >=2.5.0):
#   ansible-vault encrypt_string --encrypt-vault-id default --name name secret
# To encrypt a variable to the EC2 vault id:
#   ansible-vault encrypt_string --encrypt-vault-id ec2 --name name secret
# See ansible.cfg for notes about which vault id to use.

# Use terraform (see terraform directory) to actually provision ec2 infrastructure

- name: Validate not in multiple requires_ groups
  hosts: all
  gather_facts: false
  tags: facts
  tasks:
    - name: Ensure host is not in multiple requires_* groups
      assert:
        that:
          - "(['requires_mysql', 'requires_mysql_5', 'requires_postgresql'] | select('in', group_names) | list | length) <= 1"
        fail_msg: "{{ inventory_hostname }} is in multiple exclusive groups: {{ ['requires_mysql', 'requires_mysql_5', 'requires_postgresql'] | select('in', group_names) | list }}"

# Ensure python3 is available for Ansible (required before gather_facts), with fallback to python2
# If it does fall back, set ansible_python_interpreter to /usr/bin/python in that old group
- hosts: all
  become: true
  gather_facts: false
  tags: python
  tasks:
    - name: Install python3 for Ansible if available, otherwise fallback to python2
      raw: >-
        test -e /usr/bin/python3 ||
        (apt -y update && apt install -y python-is-python3) ||
        test -e /usr/bin/python ||
        apt install -y python-minimal
      changed_when: false

- hosts: all
  name: "Install python2 requirements"
  tags:
    - python
    - python2
  become: true
  tasks:
    - name: Install python2 packages
      tags: python
      apt:
        pkg: "{{ item }}"
        cache_valid_time: 300
      loop:
        - python-pip
        - python-pymysql
        - python-psycopg2
      when: ansible_python_version is version('3', '<')

    - name: Install boto which is required for EC2 stuff (Python 2)
      tags: python
      pip: name=boto
      when: ansible_python_version is version('3', '<')

- hosts: all
  name: "Install python3 requirements"
  tags:
    - python
    - python3
  become: true
  tasks:
    - name: Install python packages
      tags: python
      apt:
        pkg: "{{ item }}"
        cache_valid_time: 300
      loop:
        - python3-pip
        - python3-pymysql
        - python3-psycopg2
      when: ansible_python_version is version('3', '>=')

    - name: Install boto3 which is required for EC2 stuff (Python 3)
      tags: python
      pip: name=boto3
      when: ansible_python_version is version('3', '>=')

- hosts: ec2
  name: "Gather RDS facts"
  tags:
    - rds
    - facts
  become: true
  tasks:
    - name: Get information about the RDS instance
      rds:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        command: facts
        instance_name: "{{ db_name }}"
        region: "{{ ec2_region }}"
      register: rds_database
      tags:
      - facts
      - rds
      # Run this task even when running ansible-playbook with "--check"
      check_mode: false
      when: "db_name is defined"

    - name: Display information about the RDS database
      debug:
        var: "rds_database"
      tags:
        - facts
        - rds
      when: "(show_rds_debug | default(false) | bool) and (db_name is defined)"

- hosts: ec2
  become: true
  name: "RDS_planningalerts facts"
  tasks:
    - name: Get information about the planningalerts RDS instance
      rds:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        command: facts
        instance_name: "{{ planningalerts_db_name }}"
        region: "{{ ec2_region }}"
      register: rds_planningalerts
      tags:
        - facts
        - rds
      # Run this task even when running ansible-playbook with "--check"
      check_mode: false
      when: "planningalerts_db_name is defined"

    - name: Displays information about the planningalerts RDS instance
      debug:
        var: "rds_planningalerts"
      tags:
        - facts
        - rds
      when: "(show_rds_debug | default(false) | bool) and (planningalerts_db_name is defined)"

- hosts: all
  tags: base-server
  become: true
  name: "Install base server packages"
  roles:
    - internal/base-server

- hosts: all
  name: "Remove unused ruby managers"
  become: true
  tags:
    - cleanup
    - ruby
  tasks:
    - name: Remove rbenv
      tags:
        - rbenv
      import_role:
        name: internal/remove_rbenv
      vars:
        rbenv_users:
          - deploy
      when: "ruby_manager != 'rbenv'"

    - name: Remove rvm
      tags: 
        - rvm
      import_role:
        name: internal/remove_rvm
      when: "ruby_manager != 'rvm'"


    - name: Remove mise
      import_role:
        name: internal/remove_mise
      tags:
        - mise
      when: "ruby_manager != 'mise'"

- hosts: all
  name: "Setup ruby managers and install versions"
  become: true
  tags: 
    - ruby
  tasks:
    # NOTE: rbenv uses the latest bin/ruby-build so there will usually be changes if you are checking
    - name: Install rbenv
      tags: 
        - rbenv
      import_role:
        name: external/zzet.rbenv
      vars:
        rbenv:
          env: user
          version: v1.1.2
          default_ruby: "{{ ruby_versions | first }}"
          rubies: "{{ ruby_versions | map('community.general.dict_kv', 'version') | list }}"
        rbenv_users:
          - deploy
      when: "ruby_manager == 'rbenv'"

    - name: Install rvm
      tags: 
        - rvm
      import_role:
        name: external/rvm.ruby
      vars:
        rvm1_rubies: "{{ ruby_versions }}"
        rvm1_install_flags: "--auto-dotfiles"
        rvm1_install_path: /usr/local/rvm
        rvm1_user: root
        rvm1_gpg_key_server: "hkps://keyserver.ubuntu.com"
      when: "ruby_manager == 'rvm'"
      # may need this for planningalerts
      # rvm1_rvm_version: "head"
      # rvm1_gpg_key_server: 'rvm1_gpg_key_server: "hkps://keyserver.ubuntu.com"'

    # Add deploy user to group rvm
    - name: Add deploy user to rvm group
      import_role:
        name: internal/rvm.group
      tags:
        - rvm
      when: "ruby_manager == 'rvm'"

    - name: "Install mise"
      import_role:
        name: internal/mise
      tags:
        - ruby
        - mise
      when: "ruby_manager == 'mise'"

- hosts: mysql
  name: "Vagrant MySQL Server to mimic AWS RDS"
  tags: mysql
  become: true
  roles:
    - mysql

- hosts: postgresql
  name: "Vagrant PostgreSQL Server to mimic AWS RDS"
  tags: postgresql
  become: true
  roles:
    - postgresql

- hosts: righttoknow
  tags: righttoknow
  become: true
  roles:
    - righttoknow

- hosts: planningalerts
  tags: planningalerts
  become: true
  roles:
    - planningalerts

- hosts: theyvoteforyou
  tags: theyvoteforyou
  become: true
  roles:
    - theyvoteforyou

- hosts: openaustralia
  tags: openaustralia
  become: true
  roles:
    - openaustralia

- hosts: proxy
  name: "AU Proxy for morph scrapers"
  tags: proxy
  become: true
  roles:
    - proxy

- hosts: metabase
  tags: metabase
  become: true
  roles:
    - metabase

- hosts: openvpn
  tags: openvpn
  become: true
  roles:
    - internal/openvpn

# vagrant equivalent of AWS redis service
- hosts: redis
  name: "Vagrant redis Server to mimic AWS ElastiCache"
  tags: redis
  become: true
  tasks:
    - name: Install redis
      apt:
        name: redis
    - name: Make redis listen on 0.0.0.0
      lineinfile:
        path: /etc/redis/redis.conf
        regexp: "^bind 127.0.0.1"
        line: "bind 0.0.0.0"
      notify:
        - Restart redis
  handlers:
    - name: Restart redis
      service:
        name: redis
        state: restarted
