# If you've used the included Makefile, you can run ansible-plabybook
# as `.venv/bin/ansible-playbook`; or use `. .venv/bin/activate` to activate
# the virtual environment and then run it as below.

# Run this like so:
# ansible-playbook update_ubuntu_keys.yml --check

# To run this only for hosts in ec2:
# ansible-playbook -l ec2 update_ubuntu_keys.yml --check

# To only run this for planningalerts:
# ansible-playbook update_ubuntu_keys.yml -l planningalerts --check

# To only run this for openaustralia:
# ansible-playbook update_ubuntu_keys.yml -l openaustralia --check

# Once you have confirmed that the syntax is correct, run it without --check.

- hosts: ec2
  vars:
    ansible_user: ubuntu
  roles:
    - deploy-user
