---
# handlers file for righttoknow
- name: restart varnish
  ansible.builtin.systemd_service:
    name: varnish
    daemon_reload: true
    state: restarted

- name: restart postfix
  ansible.builtin.service:
    name: postfix
    state: restarted

- name: restart rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted

- name: nginx restart
  ansible.builtin.service: name=nginx state=restarted

- name: nginx reload
  ansible.builtin.service: name=nginx state=reloaded

- name: restart opendkim
  ansible.builtin.service:
    name: opendkim
    state: restarted

- name: restart sidekiq
  ansible.builtin.systemd_service:
    name: sidekiq
    daemon_reload: true
    state: restarted
