#! /bin/sh
### BEGIN INIT INFO
# Provides:          application-righttoknow
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Provides a restart task for capistrano deployments of Right To Know
# Description:       Alaveteli expects this script to be available to restart Passenger so this restarts both staging and production
### END INIT INFO

# This example sysvinit script is based on the helpful example here:
# http://richard.wallman.org.uk/2010/02/howto-deploy-a-catalyst-application-using-fastcgi-and-nginx/

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
USER=deploy

set -e

start_daemon() {
  echo "Start: is a NOOP for the Right To Know Passenger service"
}

stop_daemon() {
  echo "Stop: is a NOOP for the Right To Know Passenger service"
}

restart_daemon() {
  echo -n "Restarting Alaveteli app server"
  touch "/srv/www/{{ stage }}/current/tmp/restart.txt"

  /etc/init.d/foi-alert-tracks-{{ stage }} restart
  /etc/init.d/foi-purge-varnish-{{ stage }} restart
}

case "$1" in
  start)
    start_daemon
    ;;
  stop)
    stop_daemon
    ;;
  reload|restart|force-reload)
    restart_daemon
    ;;
  *)
    N=/etc/init.d/alaveteli-{{ stage }}
    echo "Usage: $N {start|stop|reload|restart|force-reload}" >&2
    exit 1
    ;;
esac

exit 0
