#!/bin/bash
#
### BEGIN INIT INFO
# Provides: foi-purge-varnish-{{ stage }}
# Required-Start: $local_fs $syslog
# Required-Stop: $local_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: foi-purge-varnish-{{ stage }} is a daemon purging the Alaveteli varnish cache
# Description: foi-purge-varnish-{{ stage }} purges the Alaveteli varnish cache
### END INIT INFO
#
# foi-purge-varnish-{{ stage }} Start the Alaveteli email purge-varnish daemon

NAME=foi-purge-varnish-{{ stage }}
DAEMON=/srv/www/{{ stage }}/current/script/runner
DAEMON_ARGS="--daemon PurgeRequest.purge_all_loop"
PIDDIR=/srv/www/{{ stage }}/current/tmp/pids
PIDFILE=$PIDDIR/foi-purge-varnish.pid
LOGDIR=/srv/www/{{ stage }}/current/log
LOGFILE=$LOGDIR/foi-purge-varnish.log
DUSER=deploy
SITE_HOME=/srv/www/{{ stage }}/current
# Set RAILS_ENV - not needed if using config/rails_env.rb
RAILS_ENV=production
export RAILS_ENV

# Uncomment the following line if running under rbenv - we want this daemon to run
# in the context of the ruby version defined for the site
PATH=/home/deploy/.rbenv/shims:/usr/local/bin:/usr/bin:/bin

type varnishadm > /dev/null 2>&1 || exit

trap "" 1

export PIDFILE LOGFILE

quietly_start_daemon() {
    mkdir -p {$LOGDIR,$PIDDIR}
    chown $DUSER:$DUSER {$LOGDIR,$PIDDIR}
    /sbin/start-stop-daemon --quiet --start --pidfile "$PIDFILE" --chuid "$DUSER" --chdir "$SITE_HOME" --startas "$DAEMON" -- $DAEMON_ARGS
}

start_daemon() {
    mkdir -p {$LOGDIR,$PIDDIR}
    chown $DUSER:$DUSER {$LOGDIR,$PIDDIR}
    /sbin/start-stop-daemon --start --pidfile "$PIDFILE" --chuid "$DUSER" --chdir "$SITE_HOME" --startas "$DAEMON" -- $DAEMON_ARGS
}

stop_daemon() {
    /sbin/start-stop-daemon --stop --oknodo --retry 5 --pidfile "$PIDFILE"
}

restart() { stop; start; }

case "$1" in
  check)
      quietly_start_daemon
      if [ $? -ne 1 ]
      then
          echo "Alaveteli purge-varnish daemon was not running; now restarted"
          exit 1
      else
          exit 0
      fi
      ;;

  start)
      echo -n "Starting Alaveteli purge-varnish daemon: $NAME"
      start_daemon
      ;;

  stop)
        echo -n "Stopping Alaveteli purge-varnish daemon: $NAME"
        stop_daemon
        ;;

  restart)
      echo -n "Restarting Alaveteli purge-varnish daemon: $NAME"
      stop_daemon
      start_daemon
      ;;

  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart|check}"
    exit 1
    ;;
esac

if [ $? -eq 0 ]; then
    echo .
    exit 0
else
    echo " failed"
    exit 1
fi
