---
# tasks file for postgresql

- name: Add PostgreSQL apt repository and import its signing key
  ansible.builtin.deb822_repository:
    name: pgdg
    types: deb
    uris: https://postgresql.org
    suites: "{{ ansible_distribution_release }}-pgdg"
    components: main
    signed_by: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present
  notify: Update apt cache

- name: Flush handlers to update apt cache immediately
  ansible.builtin.meta: flush_handlers

# We're currently running 15.2 in production
- name: Install postgresql 15 server
  ansible.builtin.apt:
    name: postgresql-15

- name: Update postgresql config to bind to public ip
  ansible.builtin.lineinfile:
    dest: /etc/postgresql/15/main/postgresql.conf
    regexp: "^#?listen_addresses"
    line: "listen_addresses = '*' # what IP address(es) to listen on;"
  notify: postgresql restart

- name: Allow all connections from the outside world
  ansible.builtin.lineinfile:
    dest: /etc/postgresql/15/main/pg_hba.conf
    line: "host    all             all             0.0.0.0/0               md5"
  notify: postgresql restart

- name: Install dependency for postgresql_user
  ansible.builtin.apt:
    pkg: python3-psycopg2

- name: Create root user
  community.postgresql.postgresql_user:
    name: root
    password: "{{ rds_admin_password }}"
    role_attr_flags: CREATEDB,CREATEROLE
  become_user: postgres
