---
# tasks file for roles/internal/mysql

# We're installing mysql because that's what we're using on AWS in production
- name: Install mysql server
  ansible.builtin.apt:
    name:
      - mysql-server
      - python3-mysqldb
    update_cache: true
    cache_valid_time: 3600

- name: Update mysql config to bind to public ip
  ansible.builtin.copy:
    src: mysqld.cnf
    dest: /etc/mysql/mysql.conf.d
    mode: '0644'
  notify: mysql restart

- name: Create admin user
  ansible.mysql.mysql_user:
    name: admin
    password: "{{ rds_admin_password }}"
    priv: '*.*:ALL,GRANT'
    host: '%'
    login_unix_socket: /var/run/mysqld/mysqld.sock
