---
# tasks file for roles/internal/mysql

# We're using mysql 5.6 on AWS, but that's no longer available to install
# So here we're using the system 5.7 packages, which may cause compatibility
# issues.

- name: Install mysql 5.7 server
  apt:
    pkg: mysql-server-5.7
    update_cache: yes

- name: Install dependency for following command
  apt: pkg=python-mysqldb

- name: Update mysql config to bind to public ip
  copy:
    src: mysqld.cnf
    dest: /etc/mysql/mysql.conf.d
  notify: mysql restart

- name: Create admin user
  mysql_user:
    name: admin
    password: "{{ rds_admin_password }}"
    priv: '*.*:ALL,GRANT'
    host: '%'
