# For the time being just interested in reporting
# The weekly DMARC reports are generated by a free service at https://dmarc.postmarkapp.com/
resource "cloudflare_record" "pa_dmarc" {
  zone_id = var.planningalerts_org_au_zone_id
  name = "_dmarc.planningalerts.org.au"
  type = "TXT"
  value = "v=DMARC1; p=none; pct=100; rua=mailto:re+b1g0fn6boqu@dmarc.postmarkapp.com; sp=none; aspf=r;"
}

# For the time being just interested in reporting
# The weekly DMARC reports are generated by a free service at https://dmarc.postmarkapp.com/
# An email gets sent once per week to webmaster@righttoknow.org.au
resource "cloudflare_record" "rtk_dmarc" {
  zone_id = var.righttoknow_org_au_zone_id
  name = "_dmarc.righttoknow.org.au"
  type = "TXT"
  value = "v=DMARC1; p=none; pct=100; rua=mailto:re+aysyay6u9ct@dmarc.postmarkapp.com; sp=none; aspf=r;"
}
