---
# handlers file for cloudflare_realip

- name: reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded

- name: reload apache
  ansible.builtin.systemd:
    name: apache2
    state: reloaded
