---
# tasks file for base-server
- name: Ensure packages are installed
  ansible.builtin.apt:
    name:
    - git
    - tzdata
    - acl
    state: present
    update_cache: yes

# We have to do it like this for Ubuntu 16.04
# See https://bugs.launchpad.net/ubuntu/+source/tzdata/+bug/1554806
- name: Link to correct timezone
  ansible.builtin.file:
    src: /usr/share/zoneinfo/Australia/Sydney
    dest: /etc/localtime
    state: link
  notify: Update timezone

# TODO: Add byobu and enable it by default
# TODO: Install htop because it's awesome
# Dane: "I think btop is better than htop"
