---

- name: backup-configure | Ensure for backup user is exists
  ansible.builtin.user: "name={{ backup_user }}"

- name: backup-configure | Ensure for backup directories is exits
  ansible.builtin.file: "path={{ item }} state=directory owner={{ backup_user }} group={{ backup_group }} mode=0755"
  with_items:
    - "{{ backup_home }}"
    - "{{ backup_work }}"
    - "{{ backup_logdir }}"

- name: backup-configure | Install duply
  ansible.builtin.template: "src=duply.sh.j2 dest=/usr/local/bin/duply owner={{ backup_user }} group={{ backup_group }} mode=0755"

- name: backup-configure | Create profile directories
  ansible.builtin.file:
    path: "{{ backup_home }}/{{ item.name }}"
    state: directory
    mode: "0700"
    owner: "{{ item.user | default(backup_user) }}"
    group: "{{ item.group | default(backup_group) }}"
  with_items: "{{ backup_profiles }}"

- name: backup-configure | Configure profiles
  ansible.builtin.template:
    src: conf.j2
    dest: "{{ backup_home }}/{{ item.name }}/conf"
    owner: "{{ item.user | default(backup_user) }}"
    group: "{{ item.group | default(backup_group) }}"
    mode: "0644"
  with_items: "{{ backup_profiles }}"

- name: backup-configure | Configure exclude lists
  ansible.builtin.template:
    src: exclude.j2
    dest: "{{ backup_home }}/{{ item.name }}/exclude"
    owner: "{{ item.user | default(backup_user) }}"
    group: "{{ item.group | default(backup_group) }}"
    mode: "0644"
  with_items: "{{ backup_profiles }}"

- name: backup-configure | Configure pre scripts
  ansible.builtin.template:
    src: pre.j2
    dest: "{{ backup_home }}/{{ item.name }}/pre"
    owner: "{{ item.user | default(backup_user) }}"
    group: "{{ item.group | default(backup_group) }}"
    mode: "0644"
  with_items: "{{ backup_profiles }}"

- name: backup-configure | Configure post scripts
  ansible.builtin.template:
    src: post.j2
    dest: "{{ backup_home }}/{{ item.name }}/post"
    owner: "{{ item.user | default(backup_user) }}"
    group: "{{ item.group | default(backup_group) }}"
    mode: "0644"
  with_items: "{{ backup_profiles }}"

- name: backup-configure | Configure restore scripts
  ansible.builtin.template:
    src: restore.j2
    dest: "{{ backup_home }}/{{ item.name }}/restore"
    owner: "{{ item.user | default(backup_user) }}"
    group: "{{ item.group | default(backup_group) }}"
    mode: "0644"
  with_items: "{{ backup_profiles }}"

- name: backup-configure | Create work directories
  ansible.builtin.file:
    state: directory
    path: "{{ backup_work }}/{{ item.name }}"
    owner: "{{ item.user | default(backup_user) }}"
    group: "{{ item.group | default(backup_group) }}"
    mode: "0644"
  with_items: "{{ backup_profiles }}"

- name: backup-configure | Create temp directories
  ansible.builtin.file:
    state: directory
    path: "{{ item.temp_dir }}"
    mode: '0700'
    owner: "{{ item.user | default(backup_user) }}"
    group: "{{ item.group | default(backup_group) }}"
  with_items: "{{ backup_profiles }}"
  when: item.temp_dir is defined

- name: backup-configure | Create archive directories
  ansible.builtin.file:
    state: directory
    path: "{{ item.arch_dir }}"
    mode: '0700'
    owner: "{{ item.user | default(backup_user) }}"
    group: "{{ item.group | default(backup_group) }}"
  with_items: "{{ backup_profiles }}"
  when: item.arch_dir is defined

- name: backup-configure | Setup cron
  ansible.builtin.template:
    src: cron.j2
    dest: /etc/cron.d/backup
    owner: root
    group: root
    mode: 0644

- name: backup-configure | Create log files
  ansible.builtin.file:
    state: touch
    path: "{{ backup_logdir }}/{{ item.name }}.log"
    owner: "{{ item.user|default(backup_user) }}"
    group: "{{ item.group|default(backup_group) }}"
    mode: "0644"
  with_items: "{{ backup_profiles }}"
  changed_when: false

- name: backup-configure | Configure logrotate
  ansible.builtin.template:
    src: logrotate.j2
    dest: /etc/logrotate.d/backup
    owner: root
    group: root
    mode: 0644
