---
dependencies:

  - role: nickhammond.logrotate
    logrotate_scripts:
      - name: production
        path: "/srv/www/production/shared/log/*.log"
        options:
          - daily
          - rotate 7
          - compress
          - missingok
          - copytruncate
      - name: staging
        path: "/srv/www/staging/shared/log/*.log"
        options:
          - daily
          - rotate 7
          - compress
          - missingok
          - copytruncate
