---
- name: Remove mise binary
  file:
    state: absent
    path: '{{ item }}/.local/bin/mise'
  with_items: '{{ mise_user_homes }}'

- name: Remove mise data directory
  file:
    state: absent
    path: '{{ item }}/.local/share/mise'
  with_items: '{{ mise_user_homes }}'

- name: Remove mise config directory
  file:
    state: absent
    path: '{{ item }}/.config/mise'
  with_items: '{{ mise_user_homes }}'
