---
- name: reload apache
  ansible.builtin.service: name=apache2 state=reloaded

- name: restart apache
  ansible.builtin.service: name=apache2 state=restarted

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
