development:
  :concurrency: 1

production:
  :concurrency: 2

:queues:
  - default
  - xapian
{% if stage == 'staging' %}
  - low
{% endif %}

:limits:
  xapian: 1
{% if stage == 'staging' %}
  low: 1
{% endif %}
