---
dependencies:
  - { role: docker-server }
  - role: Stouts.backup
    backup_profiles:
      - name: "{{ discourse_server_name }}_shared"
        schedule: 0 2 * * *
        source: /var/discourse/shared/{{ discourse_server_name }}
        # TODO: Duplicity will be very confused if two different machines from the same stage try to backup
        target: "s3://s3.amazonaws.com/oaf-backups/discourse/{{ discourse_server_name }}/shared"
        exclude:
          - "*/letsencrypt"