---
- name: Install memcached
  ansible.builtin.apt:
    pkg: memcached

- name: Make memcached listen to the outside world
  ansible.builtin.lineinfile:
    path: /etc/memcached.conf
    regexp: "^-l 127.0.0.1"
    line: "-l 0.0.0.0"
  notify:
    - memchached restart

- ansible.builtin.include_tasks: database.yml

- name: Ensure that deploy owns /srv/www and /srv/www/shared
  ansible.builtin.file:
    state: directory
    owner: deploy
    group: deploy
    path: "{{ item }}"
    mode: '0755'
  with_items:
    - /srv/www/production
    - /srv/www/production/shared
    - /srv/www/production/shared/config
    - /srv/www/production/shared/config/credentials
    - /srv/www/production/shared/log
    - /srv/www/production/shared/public
    - /srv/www/production/shared/system

- name: Ensure packages to build gem native extensions are installed
  ansible.builtin.apt:
    pkg:
      - libpq-dev
      - libxml2-dev
      - libxslt1-dev
      # Needed for rgeo geos support. See https://github.com/rgeo/rgeo/issues/227#issuecomment-1145169888
      - libgeos++-dev
      - libgeos-dev

- name: Copy rails master key for production
  ansible.builtin.template:
    src: "production.key.j2"
    dest: "/srv/www/production/shared/config/credentials/production.key"
    owner: deploy
    group: deploy
    mode: '0600'

- name: Allow deploy user to control services
  ansible.builtin.template:
    src: deploy_service_control.j2
    dest: /etc/sudoers.d/deploy_service_control
    mode: '0440'
    validate: visudo -cf %s

- name: Install postfix to handle incoming email
  ansible.builtin.apt:
    pkg: postfix

- name: Update postfix transport map
  ansible.builtin.copy:
    src: transport
    dest: /etc/postfix/transport
    mode: '0644'
  notify: restart postfix

- name: Update postfix virtual alias configuration
  ansible.builtin.template:
    src: virtual_alias.j2
    dest: /etc/postfix/virtual_alias
    mode: '0644'
  notify: restart postfix

- name: Install script to handle incoming email
  ansible.builtin.template:
    src: incoming-email.sh.j2
    dest: /usr/local/bin/incoming-email.sh
    # Make it executable
    mode: 0755

# Crude way of running postconf below. Will always change things and not
# restart postfix when needed

- name: Set postfix pipe handler  # noqa: no-changed-when
  ansible.builtin.command: postconf -M -e "planningalerts/unix=planningalerts unix - n n - 50 pipe flags=R user=deploy directory=/srv/www/production/current argv=/usr/local/bin/incoming-email.sh"

- name: Set postfix virtual alias  # noqa: no-changed-when
  ansible.builtin.command:  postconf -e "virtual_alias_maps=regexp:/etc/postfix/virtual_alias"

- name: Set postfix transport maps  # noqa: no-changed-when
  ansible.builtin.command: postconf -e "transport_maps=regexp:/etc/postfix/transport"

- name: Set postfix destination  # noqa: no-changed-when
  ansible.builtin.command: postconf -e "mydestination=planningalerts.{{ base_domain }}"


# Log rotation, previously handled by the nickhammond.logrotate role
- name: Install logrotate
  ansible.builtin.apt:
    pkg: logrotate
  tags: [logrotate]

- name: Install logrotate configuration for application logs
  ansible.builtin.copy:
    src: logrotate.d/production
    dest: /etc/logrotate.d/production
    owner: root
    group: root
    mode: "0644"
  tags: [logrotate]
