---
# handlers file for planningalerts
- name: memchached restart
  ansible.builtin.service:
    name: memcached
    state: restarted

- name: restart postfix
  ansible.builtin.service:
    name: postfix
    state: restarted
