# Create fake let's encrypt directories when in development
- name: Create fake let's encrypt directories when in development
  file:
    state: directory
    path: "/etc/letsencrypt/live/{{ item }}"
  with_items:
    {% if not (standalone_staging | default(false)) %}
    - "{{ righttoknow_domain }}"
    - "test.{{ righttoknow_domain }}"
    {% else %}
    - "{{ righttoknow_domain }}"
    {% endif %}
  when: "'development' in group_names"

# We need to setup the SSL certificates before we try to configure nginx
# because otherwise nginx will try to look for non-existent certificates
- name: Copy SSL certificates for development
  copy:
    src: "{{ item }}.pem"
    # We're faking it as if these are let's encrypt certs. Makes for less magic config
    dest: "/etc/letsencrypt/live/{{ item }}/fullchain.pem"
    mode: 0644
  with_items:
    {% if not (standalone_staging | default(false)) %}
    - "{{ righttoknow_domain }}"
    - "test.{{ righttoknow_domain }}"
    {% else %}
    - "{{ righttoknow_domain }}"
    {% endif %}
  # Only run this task when this machine is the development group
  when: "'development' in group_names"
  notify: nginx restart

- name: Copy SSL keys for development
  copy:
    src: "{{ item }}.key"
    dest: "/etc/letsencrypt/live/{{ item }}/privkey.pem"
    mode: 0640
  with_items:
    {% if not (standalone_staging | default(false)) %}
    - "{{ righttoknow_domain }}"
    - "test.{{ righttoknow_domain }}"
    {% else %}
    - "{{ righttoknow_domain }}"
    {% endif %}
  # Only run this task when this machine is the development group
  when: "'development' in group_names"
  notify: nginx restart

- name: Install varnish and nginx now (for the benefit of certbot)
  apt:
    pkg: "{{ item }}"
  with_items:
    - varnish
    - nginx
  when: "'ec2' in group_names"

# TODO: When (if) we use a newer version of certbot add "--post-hook" to restart nginx after renew
- name: Install certificate using certbot
  include_role:
    name: oaf.certbot
  vars:
    certbot_certs:
      {% if not (standalone_staging | default(false)) %}
      - email: contact@oaf.org.au
        domains:
          - "{{ righttoknow_domain }}"
          - www."{{ righttoknow_domain }}"
      {% endif %}
      - email: contact@oaf.org.au
        domains:
          {% if standalone_staging | default(false) %}
          - "{{ righttoknow_domain }}"
          - www."{{ righttoknow_domain }}"
          {% else %}
          - "test.{{ righttoknow_domain }}"
          - "www.test.{{ righttoknow_domain }}"
          {% endif %}
  when: "'ec2' in group_names"
