---
- name: Ensure latest git is installed
  apt: pkg=git state=latest

- name: Ensure nginx is absent
  apt:
    name: nginx
    state: absent

- name: Ensure that /var/discourse exists
  file: path=/var/discourse owner=deploy group=deploy state=directory

- name: Get the official discourse docker image
  command: git clone https://github.com/discourse/discourse_docker.git /var/discourse creates=/var/discourse/README.md

- name: Copy over app configuration
  template: src=app.yml dest=/var/discourse/containers/app.yml owner=deploy group=deploy

- name: Bootstrap discourse app
  command: ./launcher rebuild app chdir=/var/discourse creates=/var/discourse/shared/standalone/log/rails/production.log
  notify: start discourse

- name: Copy over mail-receive configuration
  template: src=mail-receiver.yml dest=/var/discourse/containers/mail-receiver.yml owner=deploy group=deploy

- name: Rebuild mail-receiver app
  command: ./launcher rebuild mail-receiver chdir=/var/discourse 
  notify: start discourse
