---
- name: Remove rbenv profile.d script
  ansible.builtin.file:
    state: absent
    path: /etc/profile.d/rbenv.sh

- name: Remove rbenv installation
  ansible.builtin.file:
    state: absent
    path: '{{ rbenv_root }}'

- name: Remove rbenv user installations
  ansible.builtin.file:
    state: absent
    path: '~{{ item }}/.rbenv'
  with_items: '{{ rbenv_users }}'
