---
- name: Install dependency for postgresql_db
  ansible.builtin.apt:
    pkg: python3-psycopg2

- name: Ensure that we have the Docker repository key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Ensure that we have the docker repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable"

- name: Install docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin

- name: Install dependency for ansible mysql_db module
  ansible.builtin.apt:
    pkg: python3-mysqldb

- name: Install pip
  ansible.builtin.apt:
    pkg: python3-pip

- name: Create database
  community.postgresql.postgresql_db:
    login_host: "{{ db_host }}"
    login_user: root
    login_password: "{{ rds_admin_password }}"
    name: "metabase"

- name: Create posgresql role
  community.postgresql.postgresql_user:
    login_host: "{{ db_host }}"
    login_user: root
    login_password: "{{ rds_admin_password }}"
    login_db: "metabase"
    name: "metabase"
    password: "{{ db_password }}"
    no_password_changes: true

# The priv option was removed from postgresql_user in community.postgresql 4.0
- name: Give the metabase user all privileges on its database
  community.postgresql.postgresql_privs:
    login_host: "{{ db_host }}"
    login_user: root
    login_password: "{{ rds_admin_password }}"
    database: "metabase"
    type: database
    role: "metabase"
    privs: ALL

- name: Create /srv/www directory
  ansible.builtin.file:
    state: directory
    owner: deploy
    group: deploy
    mode: '0755'
    path: /srv/www

- name: Copy across docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /srv/www/docker-compose.yml
    mode: '0644'

- name: Run metabase
  community.docker.docker_compose_v2:
    project_src: /srv/www
